"""Pydantic request/response models for schools, reasons, and closures."""
from __future__ import annotations

from datetime import date, datetime
from enum import Enum

from pydantic import BaseModel, Field


# --- Schools -----------------------------------------------------------

class School(BaseModel):
    id: str
    name: str
    sidn: str | None = None


class SchoolsResponse(BaseModel):
    schools: list[School]


# --- Closure reasons ---------------------------------------------------

class ClosureReason(BaseModel):
    value: str
    label: str
    requires_makeup_default: bool


class ClosureReasonsResponse(BaseModel):
    reasons: list[ClosureReason]


# --- Closure submission ------------------------------------------------

class ClosureScope(str, Enum):
    district_wide = "District_Wide"
    multiple_schools = "Multiple_Schools"
    single_school = "Single_School"


class ClosureCreateRequest(BaseModel):
    scope: ClosureScope
    school_ids: list[str] = Field(default_factory=list)
    closure_start_date: date
    closure_end_date: date
    closure_type: str
    closure_reason: str
    hours_missed: float
    external_id: str  # idempotency key, generated by React


class ClosureCreateResponse(BaseModel):
    case_id: str
    events_created: int
    ytd_missed_days: float
    current_tier: str | None = None
    makeup_required: bool = False
    waiver_auto_created: bool = False
    waiver_case_id: str | None = None


# --- Closure events (list + detail) ------------------------------------

class ClosureEvent(BaseModel):
    id: str
    name: str | None = None
    school_id: str | None = None
    school_name: str | None = None
    closure_date: date
    closure_type: str | None = None
    closure_reason: str | None = None
    hours_missed: float | None = None
    status: str | None = None
    make_up_required: bool | None = None
    make_up_method: str | None = None
    school_year: str | None = None


class ClosuresListResponse(BaseModel):
    closures: list[ClosureEvent]
    total: int
    ytd_missed_days_by_school: dict[str, float] = Field(default_factory=dict)


class MakeupDaySummary(BaseModel):
    id: str
    makeup_date: date
    method: str | None = None
    status: str | None = None


class ClosureDetailResponse(BaseModel):
    id: str
    name: str | None = None
    school_name: str | None = None
    closure_date: date
    closure_type: str | None = None
    closure_reason: str | None = None
    hours_missed: float | None = None
    status: str | None = None
    make_up_required: bool | None = None
    source_case_id: str | None = None
    reported_by: str | None = None
    reported_date: datetime | None = None
    makeup_days: list[MakeupDaySummary] = Field(default_factory=list)
    waiver_case_id: str | None = None


# --- Cancel ------------------------------------------------------------

class ClosureCancelRequest(BaseModel):
    reason: str


class ClosureCancelResponse(BaseModel):
    success: bool
    closure_id: str
    amendment_case_id: str
